// Country data with borders - expand this with your complete dataset
const countryData = {
    'France': ['Spain', 'Italy', 'Switzerland', 'Germany', 'Belgium', 'Luxembourg', 'Andorra', 'Monaco'],
    'Germany': ['France', 'Belgium', 'Netherlands', 'Denmark', 'Poland', 'Czech Republic', 'Austria', 'Switzerland', 'Luxembourg'],
    'Poland': ['Germany', 'Czech Republic', 'Slovakia', 'Ukraine', 'Belarus', 'Lithuania', 'Russia'],
    'Spain': ['France', 'Portugal', 'Andorra'],
    'Italy': ['France', 'Switzerland', 'Austria', 'Slovenia', 'San Marino', 'Vatican City'],
    'Switzerland': ['France', 'Germany', 'Austria', 'Italy', 'Liechtenstein'],
    'Belgium': ['France', 'Germany', 'Netherlands', 'Luxembourg'],
    'Netherlands': ['Germany', 'Belgium'],
    'Czech Republic': ['Germany', 'Austria', 'Slovakia', 'Poland'],
    'Austria': ['Germany', 'Czech Republic', 'Slovakia', 'Hungary', 'Slovenia', 'Italy', 'Switzerland', 'Liechtenstein'],
    'Portugal': ['Spain'],
    'Slovakia': ['Czech Republic', 'Austria', 'Hungary', 'Ukraine', 'Poland'],
    'Hungary': ['Austria', 'Slovakia', 'Ukraine', 'Romania', 'Serbia', 'Croatia', 'Slovenia'],
    'Slovenia': ['Austria', 'Italy', 'Hungary', 'Croatia'],
    'Croatia': ['Slovenia', 'Hungary', 'Serbia', 'Bosnia and Herzegovina', 'Montenegro'],
    'Ukraine': ['Poland', 'Slovakia', 'Hungary', 'Romania', 'Moldova', 'Belarus', 'Russia'],
    'Belarus': ['Poland', 'Lithuania', 'Latvia', 'Russia', 'Ukraine'],
    'Lithuania': ['Poland', 'Belarus', 'Latvia', 'Russia'],
    'Latvia': ['Lithuania', 'Belarus', 'Russia', 'Estonia'],
    'Estonia': ['Latvia', 'Russia'],
    'Russia': ['Poland', 'Lithuania', 'Latvia', 'Estonia', 'Belarus', 'Ukraine'],
    'Denmark': ['Germany'],
    'Luxembourg': ['France', 'Germany', 'Belgium'],
    'Liechtenstein': ['Switzerland', 'Austria'],
    'Andorra': ['France', 'Spain'],
    'Monaco': ['France'],
    'San Marino': ['Italy'],
    'Vatican City': ['Italy'],
    'Romania': ['Hungary', 'Serbia', 'Bulgaria', 'Moldova', 'Ukraine'],
    'Bulgaria': ['Romania', 'Serbia', 'North Macedonia', 'Greece', 'Turkey'],
    'Serbia': ['Hungary', 'Romania', 'Bulgaria', 'North Macedonia', 'Albania', 'Montenegro', 'Bosnia and Herzegovina', 'Croatia'],
    'North Macedonia': ['Serbia', 'Bulgaria', 'Greece', 'Albania'],
    'Albania': ['Serbia', 'North Macedonia', 'Greece', 'Montenegro'],
    'Montenegro': ['Serbia', 'Albania', 'Bosnia and Herzegovina', 'Croatia'],
    'Bosnia and Herzegovina': ['Serbia', 'Montenegro', 'Croatia'],
    'Greece': ['North Macedonia', 'Bulgaria', 'Albania', 'Turkey'],
    'Turkey': ['Greece', 'Bulgaria'],
    'Moldova': ['Romania', 'Ukraine'],
    'Norway': ['Sweden', 'Finland', 'Russia'],
    'Sweden': ['Norway', 'Finland'],
    'Finland': ['Norway', 'Sweden', 'Russia'],
    'Iceland': [],
    'Ireland': ['United Kingdom'],
    'United Kingdom': ['Ireland'],
    
    // Add more countries as needed...
    // You can expand this with countries from other continents
    'Canada': ['United States'],
    'United States': ['Canada', 'Mexico'],
    'Mexico': ['United States', 'Guatemala', 'Belize'],
    'Guatemala': ['Mexico', 'Belize', 'Honduras', 'El Salvador'],
    'Belize': ['Mexico', 'Guatemala'],
    'Honduras': ['Guatemala', 'El Salvador', 'Nicaragua'],
    'El Salvador': ['Guatemala', 'Honduras'],
    'Nicaragua': ['Honduras', 'Costa Rica'],
    'Costa Rica': ['Nicaragua', 'Panama'],
    'Panama': ['Costa Rica', 'Colombia'],
    'Colombia': ['Panama', 'Venezuela', 'Brazil', 'Peru', 'Ecuador'],
    'Venezuela': ['Colombia', 'Brazil', 'Guyana'],
    'Guyana': ['Venezuela', 'Brazil', 'Suriname'],
    'Suriname': ['Guyana', 'Brazil', 'French Guiana'],
    'Brazil': ['Colombia', 'Venezuela', 'Guyana', 'Suriname', 'French Guiana', 'Uruguay', 'Argentina', 'Paraguay', 'Bolivia', 'Peru'],
    'French Guiana': ['Suriname', 'Brazil'],
    'Uruguay': ['Brazil', 'Argentina'],
    'Argentina': ['Brazil', 'Uruguay', 'Paraguay', 'Bolivia', 'Chile'],
    'Paraguay': ['Brazil', 'Argentina', 'Bolivia'],
    'Bolivia': ['Brazil', 'Paraguay', 'Argentina', 'Chile', 'Peru'],
    'Chile': ['Argentina', 'Bolivia', 'Peru'],
    'Peru': ['Colombia', 'Brazil', 'Bolivia', 'Chile', 'Ecuador'],
    'Ecuador': ['Colombia', 'Peru']
};

const allCountries = Object.keys(countryData);

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { countryData, allCountries };
}
